apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

nameSuffix: -cluster-name # Update with cluster name
patches:
#- patch: |-
#    apiVersion: v1
#    kind: Pod
#    metadata:
#      name: bmc-check
#      namespace: example-bmc-prechecks
#    spec:
#      containers:
#      - name: bmc-check
#        image: 'registry.url/ose-cli-with-jq'
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: bmc-check-creds
      namespace: example-bmc-prechecks
    stringData:
      credential: 'redfish:REPLACEME'
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: bmc-ips
      namespace: example-bmc-prechecks
    data:                                      # Update with bmc ips for cluster
      bmc-ip-list.txt: |
        host01.ilo.internal.example.com
        host02.ilo.internal.example.com
        host03.ilo.internal.example.com







