apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: networklab-imageset
spec:
  # CHANGE: update to match your target OCP release
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.21.0-x86_64
