{{- $namespaces := list }}  {{/* Initialize empty list properly */}}
{{- range .Values.statefulSets }}
  {{- $namespaces = append $namespaces .namespace }}
{{- end }}
{{- $serviceAccountName :=  include "baremetal-network-tester.serviceAccountName" .  }}
{{- $labels := include "baremetal-network-tester.labels" . | nindent 4 }}
{{- $serviceAccount := .Values.serviceAccount }}
{{- range $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ . }}
  labels:
    {{- $labels  }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $serviceAccount.automount }}
{{- end }}
